[project]
name = "firstissue-mcp"
version = "0.1.0"
description = "An MCP server for getting issues from Github that you can contribute to"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
]

[tool.uv.workspace]

